APP=main

# our code
OBJS = blinky.o

OBJS += ../rad1olib/setup.o
OBJS += ../r0ketlib/display.o
OBJS += ../r0ketlib/render.o
OBJS += ../r0ketlib/fonts/smallfonts.o
OBJS += ../r0ketlib/print.o
OBJS += ../r0ketlib/itoa.o
OBJS += ../r0ketlib/keyin.o

CFLAGS=-Wno-unused-variable -DRAD1O

RPATH=..
include ../Makefile.inc
